### ISSUE TITLE
Add more descriptive error messages

### ISSUE THREAD

**Issue by vyorkin** [seppeljordan/nix-prefetch-github#17]
Thanks for such a convenient tool!

There is one small improvement that might be worth adding.
For example executing the following command:
```sh
nix-prefetch-github cinemast libjson-rpc-cpp --rev v1.2.0
```
results in getting the stack trace and error message that looks like this:
```
TypeError: 'NoneType' object is not subscriptable
```

Instead, it may be a good idea to have some high-level descriptive error message like
"the specified tag doesn't exist" or smth like that

**Comment by seppeljordan** [comment]
Hi, this should now be fixed on nixos-19.09, nixos-unstable and nixpkgs-unstable.  closing this as a result.
