### ISSUE TITLE
Add option for fetching the repo in the working directory

### ISSUE THREAD

**Issue by expipiplus1** [seppeljordan/nix-prefetch-github#19]
At the moment I'm using something like this:

```bash
git remote get-url origin | 
  awk -F / '{print $(NF-1),"\t",$NF}' | 
  read owner repo && 
  nix-prefetch-github --prefetch --nix --rev $(git rev-parse HEAD) $owner $repo
```

It would be great to have this functionality built in with the necessary bells and whistles like warning about dirty files and being able to select a remote...

**Comment by seppeljordan** [comment]
Thank you for the feature request.

* What is the goal of this feature?
* In what situations is this useful?
* What do you expect of an implementation to offer to the user?

Looking forward to your response :)

**Comment by expipiplus1** [comment]
An example of running the above command in case it isn't clear what it's doing:

```bash
$ git clone https://github.com/seppeljordan/nix-prefetch-github
Cloning into 'nix-prefetch-github'...
remote: Enumerating objects: 73, done.
remote: Counting objects: 100% (73/73), done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 345 (delta 28), reused 40 (delta 15), pack-reused 272
Receiving objects: 100% (345/345), 81.23 KiB | 192.00 KiB/s, done.
Resolving deltas: 100% (155/155), done.

$ cd nix-prefetch-github

$ git checkout f043e83500a65729110f61b371ff89f079725326

$ git remote get-url origin |
  awk -F / '{print $(NF-1),"\t",$NF}' |
  read owner repo &&
  nix-prefetch-github --prefetch --nix --rev $(git rev-parse HEAD) $owner $repo
let
  pkgs = import <nixpkgs> {};
in
  pkgs.fetchFromGitHub {
    owner = "seppeljordan";
    repo = "nix-prefetch-github";
    rev = "f043e83500a65729110f61b371ff89f079725326";
    sha256 = "1nh136ir5q9j84wjcrn9qvw8v3vdpmdayfhq8z853yl4wljmcxfb";
  }
```

Note that the `rev` attribute is the commit at which the repo is checked out.

- The goal would be to have functionality in nix-prefetch-github such that one could (from a git repo) create a nix expression to fetch the repo at it's current revision from github
- I have used this most often as such: 
  - Fork a repo
  - Make changes locally
  - Push to GitHub
  - Use the above command to generate a nix expression to quickly use this fork in my overlays
- This will offer all of the above to the user :)

**Comment by seppeljordan** [comment]
This sounds reasonable, and will I consider implementing it.  If someone would come and implement this instead, I would definitely merge this into master.  In any case, I think that this should be a separate command from from `nix-prefetch-github` though, but could be provided from the same python package.

**Comment by seppeljordan** [comment]
@expipiplus1 
It has been a while, but I implemented the feature on master and will release it soon-ish on nixpkgs.

I will close this issue.  Feel free to reopen it, if you have feedback.

**Comment by expipiplus1** [comment]
Thanks! What's the argument for using this command?

**Comment by seppeljordan** [comment]
Hi,

the command will be called "nix-prefetch-github-local".

cheers

**Comment by expipiplus1** [comment]
Thanks!

**Comment by seppeljordan** [comment]
@expipiplus1 Just wanted to let you know that the version 3.0 is about to be merged into nixpkgs master.  Check out https://github.com/NixOS/nixpkgs/pull/96546 for more info on current progress.

**Comment by expipiplus1** [comment]
super! Thanks again!
