### ISSUE TITLE
Regression: Fails when --rev is a branch or a tag containing the '/' character

### ISSUE THREAD

**Issue by jraygauthier** [seppeljordan/nix-prefetch-github#22]
See https://github.com/seppeljordan/nix-prefetch-github/blob/638d8b062d4549927ca3647b69e06a540f63f8ec/src/nix_prefetch_github/list_remote.py#L23

```ipython
In [4]: _, b, c = "refs/heads/my/branch".split('/')                                                                                                   
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-97c5e99b63b0> in <module>
----> 1 _, b, c = "refs/heads/my/branch".split('/')

ValueError: too many values to unpack (expected 3)
```

The entry is skipped.

**Comment by jraygauthier** [comment]
Note that same problem might occurs with the HEAD case parsing <https://github.com/seppeljordan/nix-prefetch-github/blob/638d8b062d4549927ca3647b69e06a540f63f8ec/src/nix_prefetch_github/list_remote.py#L19>

**Comment by jraygauthier** [comment]
Note: was working fine with 2.2 using full path to ref which no longer works using the current version: #24 .

**Comment by seppeljordan** [comment]
Will be fixed in next version (coming soon).  Thank you for reporting
