### ISSUE TITLE
Specify release

### ISSUE THREAD

**Issue by M-Gregoire** [seppeljordan/nix-prefetch-github#3]
First of all, thank you for this package!

Is it possible to specify the release in `nix-prefetch-github` using CLI? I couldn't find anything in the README and there is no man page for it.

Thank you!

**Comment by seppeljordan** [comment]
Hi @M-Gregoire,

sorry for the late response.  Should be able to archive that with the `--rev` flag.  Let's say you want to fetch release `v1.8` of the repo `owner/project`.  The command to archive that would be:

```
nix-prefetch-github owner project --rev v1.8
```

I hope this information is still useful to you.

**Comment by M-Gregoire** [comment]
Hi @seppeljordan ,
Thank you for your answer, It might be useful for my next derivation!
