### ISSUE TITLE
Feature: adding support for fetch submodules?

### ISSUE THREAD

**Issue by Rizary** [seppeljordan/nix-prefetch-github#30]
Since `fetchFromGithub` already has `fetchSubmodules`, it will be better to nix-prefetch-github have the same options.

**Comment by seppeljordan** [comment]
Hi,

thanks for your feature request.  Can you point me to a github repository which uses submodules so I can use it for testing?

Cheers

**Comment by Rizary** [comment]
Hi!!

Sure, github.com/hasktorch/hasktorch

The submodule is under the `deps` folder
