### ISSUE TITLE
Fetch latest release

### ISSUE THREAD

**Issue by adisbladis** [seppeljordan/nix-prefetch-github#32]
Currently (afaik) `nix-prefetch-github` just probes the latest commit and generates output for that commit.
I'd like to have a flag to fetch the latest release to avoid a manual round trip to the github api.

**Comment by seppeljordan** [comment]
Hi,

To implement such a feature we would have to define what you mean by "latest release". The release with the "highest" version number or the most recent release?  How do you expect the program to behave when there is a weird versioning scheme going on in the target repo?  What should happen if there is no release?

Thanks for your feature request.

**Comment by adisbladis** [comment]
Github has a notion of what it considers to be the latest release: `curl https://api.github.com/repos/python-poetry/poetry/releases/latest`.
I'd expect `nix-prefetch-github` to pick that one.

**Comment by seppeljordan** [comment]
Thank you for your feedback.  I'll try to work it into the next release.

**Comment by seppeljordan** [comment]
Hi, unfortunately this feature did not make it into the current release, but it is still planned for a future release.

**Comment by seppeljordan** [comment]
Hi @adisbladis ,
the requested feature just landed on master.  The package can easily be installed as a flake.  Let me know if installing the package as a flake is not an option for you.  Feedback is very much welcome (especially before formally releasing the feature into wild).

You can prefetch the latest release of a package via the newly added command `nix-prefetch-github-latest-release`.

cheers

**Comment by seppeljordan** [comment]
Okay. This was merged into nixpkgs with https://github.com/NixOS/nixpkgs/pull/102386
