### ISSUE TITLE
Fetch submodules flag is always on

### ISSUE THREAD

**Issue by SuperSandro2000** [seppeljordan/nix-prefetch-github#37]
The ``--fetch-submodules`` flag is broken and not respected. Whether I pass it or not the resulting hash is always the same.

**Comment by seppeljordan** [comment]
@SuperSandro2000  Can you please provide an example?

**Comment by SuperSandro2000** [comment]
```
 ➜ , nix-prefetch-github SuperSandro2000 supersandro.de
[2 copied (0.3 MiB), 0.1 MiB DL]
{
    "owner": "SuperSandro2000",
    "repo": "supersandro.de",
    "rev": "1ccda8a2503bc6372d93ec36986dd0257634891e",
    "sha256": "0bax0lq8awbiff04ha9yqlfzajvrkf7gfmxajdlbakmlpzfy0sbk",
    "fetchSubmodules": true
}
```
```
 ➜ , nix-prefetch-github --fetch-submodules SuperSandro2000 supersandro.de
{
    "owner": "SuperSandro2000",
    "repo": "supersandro.de",
    "rev": "1ccda8a2503bc6372d93ec36986dd0257634891e",
    "sha256": "1ik3ziz4w2v71b33g73yj8h4vrvbl7waiwlbikgsd0fxjs5x98wf",
    "fetchSubmodules": true
}
```

Strange. Now the hash is different. Last time I checked it was the same with both commands. The fetchSubmodules flag is still wrong.

**Comment by seppeljordan** [comment]
@SuperSandro2000 Can you post the result of `nix-prefetch-github --version` to this thread? Thanks

**Comment by SuperSandro2000** [comment]
```
nix-prefetch-github, version 3.0
```

**Comment by seppeljordan** [comment]
@SuperSandro2000 Version 4.0 with this issue fixed is released to pypi.  I will request an update in nixpkgs soon-ish.  Thank you for reporting this issue.
