### ISSUE TITLE
Error: Internal Error: Calculate hash value for sources

### ISSUE THREAD

**Issue by bbigras** [seppeljordan/nix-prefetch-github#4]
I think I'm using nix-prefetch-github from NixOS stable channel.

`/nix/store/l2pwcxh72i854q3dpn2gzwwa558d309l-nix-prefetch-github-1.3/bin/nix-prefetch-github`

```
$ nix-prefetch-github --rev 3e704f3b3f55d7a864efb2a3ae2d84e3a54512bc bbigras wlroots

Error: Internal Error: Calculate hash value for sources in github repo bbigras/wlroots.

output was: building '/nix/store/rfjcq0fcmiz7masslf7q27xs012v6mnp-source.drv'...

trying https://github.com/bbigras/wlroots/archive/3e704f3b3f55d7a864efb2a3ae2d84e3a54512bc.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   157    0   157    0     0    585      0 --:--:-- --:--:-- --:--:--   583
100  459k    0  459k    0     0   655k      0 --:--:-- --:--:-- --:--:--  655k
unpacking source archive /build/3e704f3b3f55d7a864efb2a3ae2d84e3a54512bc.tar.gz
hash mismatch in fixed-output derivation '/nix/store/7pzdkrl1ddw9blkr4jymwavbxmxxdwm1-source':
  wanted: sha256:1y4ly7lgqm03wap4mh01yzcmvryp29w739fy07zzvz15h2z9x3dv
  got:    sha256:0x1x9dq4hnkdrdfbvcm6kaivrkgmmr4vp2qqwz15y5pcawvyd0z6
error: build of '/nix/store/rfjcq0fcmiz7masslf7q27xs012v6mnp-source.drv' failed
```

**Comment by seppeljordan** [comment]
Hi,

thank you for reporting this issue and sorry for the late response.  Can you tell me which channel you are on exactly? That would help me a lot in fixing the issue.

**Comment by bbigras** [comment]
- system: `"x86_64-linux"`
 - host os: `Linux 4.19.16, NixOS, 19.03.git.bc41317 (Koi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.2`
 - channels(root): `"nixos-18.09.2117.b01a89d58f1, nixos-unstable-19.03pre168555.ce8c2436998"`
 - channels(bbigras2): `"home-manager-18.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

I'm following the unstable channel for my configuration.nix (to run sway with https://github.com/colemickens/nixpkgs-wayland) but I think I'm using the sable channel for most applications.

I installed `nix-prefetch-github` with `home-manager`.

maybe the path in the hash could help:
/nix/store/bpzfs7wxffsddnrm3j6v48cc3s9zpfkp-home-manager-path/bin/nix-prefetch-github

**Comment by vorot93** [comment]
Same on latest unstable:

```
$ nix-shell -p nix-prefetch-github --run "nix-prefetch-github seppeljordan nix-prefetch-github"
Error: Internal Error: Calculate hash value for sources in github repo seppeljordan/nix-prefetch-github.

output was: building '/nix/store/849maqpzs5mc4d05js675m0xg54a9xdp-source.drv'...

trying https://github.com/seppeljordan/nix-prefetch-github/archive/cffdbcb3351f500b5ca8867a65261443b576b215.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   174    0   174    0     0    215      0 --:--:-- --:--:-- --:--:--   215
100 12396    0 12396    0     0   7480      0 --:--:--  0:00:01 --:--:-- 37677
unpacking source archive /build/cffdbcb3351f500b5ca8867a65261443b576b215.tar.gz
hash mismatch in fixed-output derivation '/nix/store/ddcsgfa91ygycqn55y2f5ym9sa7m75sd-source':
  wanted: sha256:1y4ly7lgqm03wap4mh01yzcmvryp29w739fy07zzvz15h2z9x3dv
  got:    sha256:06vxy26d1s7azb9amxdf83i8kxgs2sbjsy0d3mjhwffga13b4igc
error: build of '/nix/store/849maqpzs5mc4d05js675m0xg54a9xdp-source.drv' failed
```

**Comment by seppeljordan** [comment]
Thank you all for your reports.  I figured out the problem and will supply a fixed version for nixpkgs shorty.  This error should now be fixed on `master` of `nix-prefetch-github`.

**Comment by seppeljordan** [comment]
I opened a [PR in nixpkgs](https://github.com/NixOS/nixpkgs/pull/56296) to include the fix .

**Comment by mitchellwrosen** [comment]
I'm still seeing this on the latest unstable.

```
$ nix-prefetch-github seppeljordan nix-prefetch-github
Internal Error: Calculate hash value for sources in github repo seppeljordan/nix-prefetch-github.
```

**Comment by seppeljordan** [comment]
@mitchellwrosen Hi, please open a new issue including which nix version you use.

**Comment by seppeljordan** [comment]
@mitchellwrosen Hi, please open a new issue including which nix version you use.
