### ISSUE TITLE
Missing `leaveDotGit` and `deepClone`

### ISSUE THREAD

**Issue by thiagokokada** [seppeljordan/nix-prefetch-github#41]
`fetchFromGitHub` also support those two options: https://nixos.org/manual/nixpkgs/stable/#fetchfromgithub

It would be interesting to have support in this project too, so we can use it in more contexts.

**Comment by seppeljordan** [comment]
Thanks for reporting. I think that this is a good idea.

**Comment by seppeljordan** [comment]
@thiagokokada Hi, I implemented the feature and the PR for merging into nixpkgs is submitted.

**Comment by thiagokokada** [comment]
Is there no more way to use `nix-prefetch-github` as a Python library? Asking this because after merging your PR, this script doesn't work anymore: https://github.com/NixOS/nixpkgs/commit/6f05bc3791cd7d27cdc376548df4ce05d9a4ce6d

There isn't many usages of it on nixpkgs (the only other that I found is this one: thttps://github.com/NixOS/nixpkgs/commit/6f05bc3791cd7d27cdc376548df4ce05d9a4ce6d), however not sure if breaking the compatibility is a good idea.

**Comment by thiagokokada** [comment]
Did a PR to fix the issue, avoiding using `nix-prefetch-github` as a lib: https://github.com/NixOS/nixpkgs/pull/153401

Thanks @seppeljordan, closing this issue.

**Comment by seppeljordan** [comment]
Thanks for your flexibility. I am sorry for the lacking backwards compatibility.
