### ISSUE TITLE
rev different betwen nix-prefetch-git and prefetch-github

### ISSUE THREAD

**Issue by Rizary** [seppeljordan/nix-prefetch-github#9]
Hi, if I am running `nix-prefetch-github --nix` without specify `--rev` option, why the result is different from `nix-prefetch-git` command?

`nix-prefetch-github` seems prefetch old `rev` instead of newest like `nix-prefetch-git` did. Can you explain about this?Is this intended result from `nix-prefetch-github`?

**Comment by seppeljordan** [comment]
Hi, thanks for reporting this.  This is a bug and will be fixed soon-ish.

**Comment by Rizary** [comment]
@seppeljordan nice!! sorry I can't help you fixed that since I am not familiar with the code.

**Comment by seppeljordan** [comment]
@Rizary This change is now merged into master of nixpkgs.  This means that the bug should be fixed with the next update nixpkgs-unstable/nixos-unstable.  If you need instruction on how to use the latest release on the stable branch of nixpkgs, let me know.

**Comment by Rizary** [comment]
@seppeljordan thanks!!! unstable is fine for me.
